### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ran-dall**
Updated README.md with Homebrew Cask install instructions

### CODE REVIEW

**Comment by edanchenkov** [comment]
Do you know why `brew cask info menutube` returns `Error: Cask 'menutube' is unavailable: No Cask with this name exists.`?

**Comment by ran-dall** [comment]
```bash
$ brew cask info menutube
menutube: 1.4.0
https://edanchenkov.github.io/MenuTube/
/usr/local/Caskroom/menutube/1.4.0 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/menutube.rb
==> Name
MenuTube
==> Artifacts
MenuTube.app (App)
```

Try `brew upgrade` and see if it updates your install of `brew`. Otherwise, run `brew doctor` and send me the output.

**Comment by edanchenkov** [comment]
Yep, apparently `info` command does not run `update`, unlike `install`. Got it now. I will merge this PR. Thanks!

**Comment by ran-dall** [comment]
@edanchenkov Just putting it out there, but it might be worth an idea to back up the formula, in case it ever gets removed from HBC. People can always install directly through a `URL` like what I did on the issue. If you'd like I can do it for you and make a PR with the backup.

**Comment by edanchenkov** [comment]
Sounds great, go ahead.

**Pull request merged**
